import { Geist, Geist_Mono } from "next/font/google";

import Photo from "./components/Photo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full m-auto gap-48 flex justify-center items-center`}
      >
        {children}

        <Photo />
      </body>
    </html>
  );
}
